<?php

namespace Kata\Ingredient;

use Kata\Ingredient;

class Fromage extends Ingredient
{
    public function __construct()
    {
        parent::__construct('fromage', true, true);
    }

    public function isFromage()
    {
        return true; // TODO: Change the autogenerated stub
    }
}
